from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal

import pandas as pd
import pytest
from sqlalchemy import Engine
from sqlalchemy.orm import Session

from src.database.base import DatabaseBase
from src.database.models import (
    ClientModel,
    PortfolioModel,
)
from src.database.persistence_service import (
    RebalancePersistenceService,
)
from src.database.repositories import (
    RebalanceRunRepository,
)
from src.database.session import (
    create_database_engine,
    create_database_session_factory,
)


@pytest.fixture
def database_engine() -> Engine:
    """Create an isolated in-memory database."""

    engine = create_database_engine(
        "sqlite+pysqlite:///:memory:"
    )

    DatabaseBase.metadata.create_all(engine)

    try:
        yield engine
    finally:
        DatabaseBase.metadata.drop_all(engine)
        engine.dispose()


@pytest.fixture
def database_session(
    database_engine: Engine,
) -> Session:
    """Create one database session."""

    factory = create_database_session_factory(
        database_engine
    )

    with factory() as session:
        yield session


@pytest.fixture
def persisted_portfolio(
    database_session: Session,
) -> PortfolioModel:
    """Persist and return one portfolio."""

    client = ClientModel(
        client_id="C00001",
        risk_category="balanced",
    )

    portfolio = PortfolioModel(
        portfolio_id="P00001",
        portfolio_value=Decimal("1000000.00"),
    )

    client.portfolios.append(portfolio)

    database_session.add(client)
    database_session.commit()

    return portfolio


def _build_trade_results() -> pd.DataFrame:
    """Build final deterministic pipeline output."""

    audit_timestamp = datetime(
        2026,
        8,
        4,
        10,
        0,
        tzinfo=timezone.utc,
    )

    return pd.DataFrame(
        [
            {
                "portfolio_id": "P00001",
                "asset": "domestic_equity",
                "action": "SELL",
                "current_weight": 0.60,
                "trade_weight": -0.02,
                "post_trade_weight": 0.58,
                "trade_value": -20_000.0,
                "transaction_cost": 40.0,
                "estimated_tax_liability": 400.0,
                "threshold_breached": True,
                "threshold_severity": "high",
                "breach_ratio": 1.5,
                "final_trigger_type": "threshold",
                "final_priority": "high",
                "contributing_triggers": (
                    "threshold, calendar"
                ),
                "client_explanation": (
                    "Domestic equity will be reduced."
                ),
                "advisor_explanation": (
                    "Sell domestic equity."
                ),
                "compliance_explanation": (
                    "Trade generated by optimizer."
                ),
                "approval_required": False,
                "approval_status": "NOT_REQUIRED",
                "approval_reason": (
                    "Automatic approval."
                ),
                "audit_id": "AUD000001",
                "audit_timestamp": audit_timestamp,
            },
            {
                "portfolio_id": "P00001",
                "asset": "fixed_income",
                "action": "BUY",
                "current_weight": 0.30,
                "trade_weight": 0.02,
                "post_trade_weight": 0.32,
                "trade_value": 20_000.0,
                "transaction_cost": 40.0,
                "estimated_tax_liability": 0.0,
                "threshold_breached": True,
                "threshold_severity": "high",
                "breach_ratio": 1.5,
                "final_trigger_type": "threshold",
                "final_priority": "high",
                "contributing_triggers": (
                    "threshold, calendar"
                ),
                "client_explanation": (
                    "Fixed income will be increased."
                ),
                "advisor_explanation": (
                    "Buy fixed income."
                ),
                "compliance_explanation": (
                    "Trade generated by optimizer."
                ),
                "approval_required": False,
                "approval_status": "NOT_REQUIRED",
                "approval_reason": (
                    "Automatic approval."
                ),
                "audit_id": "AUD000002",
                "audit_timestamp": audit_timestamp,
            },
        ]
    )


def test_service_persists_complete_rebalance_graph(
    database_session: Session,
    persisted_portfolio: PortfolioModel,
) -> None:
    repository = RebalanceRunRepository(
        database_session
    )
    service = RebalancePersistenceService(
        repository
    )

    result = service.persist_rebalance_result(
        portfolio=persisted_portfolio,
        trade_results=_build_trade_results(),
        portfolio_value=Decimal("1000000.00"),
        transaction_cost_rate=Decimal("0.002"),
        run_id="RUN000001",
        completed_at=datetime.now(
            timezone.utc
        ),
    )

    assert result.id is not None
    assert result.run_id == "RUN000001"
    assert len(result.trades) == 2

    first_trade = result.trades[0]

    assert first_trade.approval is not None
    assert first_trade.audit_record is not None


def test_service_preserves_signed_trade_values(
    database_session: Session,
    persisted_portfolio: PortfolioModel,
) -> None:
    service = RebalancePersistenceService(
        RebalanceRunRepository(
            database_session
        )
    )

    result = service.persist_rebalance_result(
        portfolio=persisted_portfolio,
        trade_results=_build_trade_results(),
        portfolio_value=Decimal("1000000.00"),
        transaction_cost_rate=Decimal("0.002"),
    )

    trades_by_asset = {
        trade.asset: trade
        for trade in result.trades
    }

    assert (
        trades_by_asset[
            "domestic_equity"
        ].trade_value
        == Decimal("-20000.00")
    )

    assert (
        trades_by_asset[
            "fixed_income"
        ].trade_value
        == Decimal("20000.00")
    )


def test_service_does_not_mutate_dataframe(
    database_session: Session,
    persisted_portfolio: PortfolioModel,
) -> None:
    trade_results = _build_trade_results()
    original = trade_results.copy(deep=True)

    service = RebalancePersistenceService(
        RebalanceRunRepository(
            database_session
        )
    )

    service.persist_rebalance_result(
        portfolio=persisted_portfolio,
        trade_results=trade_results,
        portfolio_value=Decimal("1000000.00"),
        transaction_cost_rate=Decimal("0.002"),
    )

    pd.testing.assert_frame_equal(
        trade_results,
        original,
    )


def test_missing_required_column_is_rejected(
    database_session: Session,
    persisted_portfolio: PortfolioModel,
) -> None:
    trade_results = _build_trade_results().drop(
        columns=["transaction_cost"]
    )

    service = RebalancePersistenceService(
        RebalanceRunRepository(
            database_session
        )
    )

    with pytest.raises(
        ValueError,
        match="missing required columns",
    ):
        service.persist_rebalance_result(
            portfolio=persisted_portfolio,
            trade_results=trade_results,
            portfolio_value=Decimal("1000000.00"),
            transaction_cost_rate=Decimal("0.002"),
        )


def test_multiple_portfolios_are_rejected(
    database_session: Session,
    persisted_portfolio: PortfolioModel,
) -> None:
    trade_results = _build_trade_results()
    trade_results.loc[
        trade_results.index[-1],
        "portfolio_id",
    ] = "P00002"

    service = RebalancePersistenceService(
        RebalanceRunRepository(
            database_session
        )
    )

    with pytest.raises(
        ValueError,
        match="exactly one portfolio",
    ):
        service.persist_rebalance_result(
            portfolio=persisted_portfolio,
            trade_results=trade_results,
            portfolio_value=Decimal("1000000.00"),
            transaction_cost_rate=Decimal("0.002"),
        )


def test_unpersisted_portfolio_is_rejected(
    database_session: Session,
) -> None:
    portfolio = PortfolioModel(
        portfolio_id="P00001",
        portfolio_value=Decimal("1000000.00"),
    )

    service = RebalancePersistenceService(
        RebalanceRunRepository(
            database_session
        )
    )

    with pytest.raises(
        ValueError,
        match="must be persisted",
    ):
        service.persist_rebalance_result(
            portfolio=portfolio,
            trade_results=_build_trade_results(),
            portfolio_value=Decimal("1000000.00"),
            transaction_cost_rate=Decimal("0.002"),
        )