"""create initial portfolio tables

Revision ID: b2848ade209a
Revises: 
Create Date: 2026-08-05 19:25:02.724136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2848ade209a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('risk_category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('portfolio_value > 0', name='ck_portfolios_positive_value'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_client_id'), 'portfolios', ['client_id'], unique=False)
    op.create_index('ix_portfolios_client_id_created_at', 'portfolios', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_portfolios_portfolio_id'), 'portfolios', ['portfolio_id'], unique=True)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=100), nullable=False),
    sa.Column('current_weight', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_basis >= 0', name='ck_portfolio_holdings_non_negative_cost_basis'),
    sa.CheckConstraint('current_value >= 0', name='ck_portfolio_holdings_non_negative_value'),
    sa.CheckConstraint('current_weight >= 0 AND current_weight <= 1', name='ck_portfolio_holdings_weight_range'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset', name='uq_portfolio_holdings_portfolio_asset')
    )
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_table('rebalance_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_cost_rate', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('portfolio_value > 0', name='ck_rebalance_runs_positive_portfolio_value'),
    sa.CheckConstraint('transaction_cost_rate >= 0 AND transaction_cost_rate <= 1', name='ck_rebalance_runs_cost_rate_range'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebalance_runs_portfolio_id'), 'rebalance_runs', ['portfolio_id'], unique=False)
    op.create_index('ix_rebalance_runs_portfolio_started_at', 'rebalance_runs', ['portfolio_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_rebalance_runs_run_id'), 'rebalance_runs', ['run_id'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rebalance_run_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('current_weight', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('trade_weight', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('post_trade_weight', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('trade_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estimated_tax_liability', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('threshold_breached', sa.Boolean(), nullable=False),
    sa.Column('threshold_severity', sa.String(length=30), nullable=False),
    sa.Column('breach_ratio', sa.Numeric(precision=12, scale=10), nullable=False),
    sa.Column('final_trigger_type', sa.String(length=50), nullable=False),
    sa.Column('final_priority', sa.String(length=30), nullable=False),
    sa.Column('contributing_triggers', sa.Text(), nullable=False),
    sa.Column('client_explanation', sa.Text(), nullable=False),
    sa.Column('advisor_explanation', sa.Text(), nullable=False),
    sa.Column('compliance_explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('BUY', 'SELL', 'HOLD')", name='ck_trades_valid_action'),
    sa.CheckConstraint('current_weight >= 0 AND current_weight <= 1', name='ck_trades_current_weight_range'),
    sa.CheckConstraint('estimated_tax_liability >= 0', name='ck_trades_non_negative_tax'),
    sa.CheckConstraint('post_trade_weight >= 0 AND post_trade_weight <= 1', name='ck_trades_post_trade_weight_range'),
    sa.CheckConstraint('transaction_cost >= 0', name='ck_trades_non_negative_transaction_cost'),
    sa.ForeignKeyConstraint(['rebalance_run_id'], ['rebalance_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rebalance_run_id', 'asset', name='uq_trades_run_asset')
    )
    op.create_index(op.f('ix_trades_rebalance_run_id'), 'trades', ['rebalance_run_id'], unique=False)
    op.create_index('ix_trades_run_action', 'trades', ['rebalance_run_id', 'action'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('approval_reason', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='uq_approvals_trade_id')
    )
    op.create_index(op.f('ix_approvals_trade_id'), 'approvals', ['trade_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=50), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('audit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='uq_audit_records_trade_id')
    )
    op.create_index(op.f('ix_audit_records_audit_id'), 'audit_records', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_records_trade_id'), 'audit_records', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_records_trade_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_audit_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_approvals_trade_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_trades_run_action', table_name='trades')
    op.drop_index(op.f('ix_trades_rebalance_run_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_rebalance_runs_run_id'), table_name='rebalance_runs')
    op.drop_index('ix_rebalance_runs_portfolio_started_at', table_name='rebalance_runs')
    op.drop_index(op.f('ix_rebalance_runs_portfolio_id'), table_name='rebalance_runs')
    op.drop_table('rebalance_runs')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_portfolios_portfolio_id'), table_name='portfolios')
    op.drop_index('ix_portfolios_client_id_created_at', table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_client_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
